spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD:root}

  kafka:
    bootstrap-servers: kafka:9092

  mail:
    host: ${EMAIL_HOST:mailhog}
    port: ${EMAIL_PORT:1025}
    username: ${EMAIL_USER:}
    password: ${EMAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_SMTP_AUTH:false}
          starttls:
            enable: ${EMAIL_SMTP_STARTTLS:false}
            required: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/event-ticketing
          jwk-set-uri: http://keycloak:8080/realms/event-ticketing/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://keycloak:8080
  realm: event-ticketing
  client-id: event-ticketing-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    username: ${KEYCLOAK_ADMIN:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: user-service

app:
  email-verification:
    base-url: ${EMAIL_VERIFICATION_BASE_URL:http://localhost:8080/api/auth/email/verify?token=}
