spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ticket_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

  kafka:
    bootstrap-servers: kafka:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tisqra
          jwk-set-uri: http://keycloak:8080/realms/tisqra/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: ticket-service

tisqra:
  flyway:
    repair-on-startup: true

